SeeMoreApp.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SeeMoreApp.Domain.Abstract;
using SeeMoreApp.Domain.Entities;
using SeeMoreApp.WebUI.Models;

namespace SeeMoreApp.WebUI.Controllers
{
    public class CartController : Controller
    {

//        For the AddToCart and RemoveFromCart methods, we have used parameter names that match the 
//input elements in the HTML forms we created in the ProductSummary.cshtml view. This allows the MVC 
//Framework to associate incoming form POST variables with those parameters, meaning we don’t need to 
//process the form ourselves.
        

//        The final point to note about the Cart controller is that both the AddToCart and RemoveFromCart methods 
//call the RedirectToAction method. This has the effect of sending an HTTP redirect instruction to the 
//client browser, asking the browser to request a new URL. In this case, we have asked the browser to 
//request a URL that will call the Index action method of the Cart controller. 

//        We have removed the GetCart method and added a Cart parameter to each of the action methods.  
//When the MVC Framework receives a request that requires, say, the  AddToCart method to be 
//invoked, it begins by looking at the parameters for the action method. It looks at the list of binders 
//available and tries to find one that can create instances of each parameter type. Our custom binder is 
//asked to create a Cart object, and it does so by working with the session state feature. Between our 
//binder and the default binder, the MVC Framework is able to create the set of parameters required to call 
//the action method. And so it does, allowing us to refactor the controller so that it has no view as to how 
//Cart objects are created when requests are received. 

//        There are a few benefits to using a custom model binder like this. The first is that we have separated 
//the logic used to create a Cart from that of the controller, which allows us to change the way we store 
//Cart objects without needing to change the controller. The second benefit is that any controller class 
//that works with Cart objects can simply declare them as action method parameters and take advantage 
//of the custom model binder. The third benefit, and the one we think is most important, is that we can 
//now unit test the Cart controller without needing to mock a lot of ASP.NET plumbing.

        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor proc) { repository = repo; orderProcessor = proc; }

//        You can see that the Checkout action method we’ve added is decorated with the HttpPost attribute, 
//which means that it will be invoked for a POST request—in this case, when the user submits the form. 
//Once again, we are relying on the model binder system, both for the ShippingDetails parameter (which 
//is created automatically using the HTTP form data) and the Cart parameter (which is created using our 
//custom binder).
        
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl) {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null) {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl) {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null) {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public ViewResult Summary(Cart cart)
        {
            return View(cart);
        }
        public ViewResult Checkout() {
            return View(new ShippingDetails());
        }

        public ViewResult Index(Cart cart, string returnUrl) { 
            return View (new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl} );
        }

        //private Cart GetCart() {
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart == null) {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}

    }
}

SeeMoreApp.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SeeMoreApp.Domain.Abstract;

namespace SeeMoreApp.WebUI.Controllers
{
    public class NavController : Controller{
        private IProductRepository repository;

        public NavController(IProductRepository repo) { repository = repo; }

        public PartialViewResult Menu(string category = null) {

            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                   .Select(x => x.Category)
                   .Distinct()
                   .OrderBy(x => x);

            return PartialView(categories);

        }
    
        //
        // GET: /Nav/


    }
}

SeeMoreApp.WebUI/Views/Shared/ProductSummary.cshtml
@model SeeMoreApp.Domain.Entities.Product

<div class="item"> 
    <h3>@Model.Name</h3> 
    @Model.Description 

 @*   By default, the BeginForm helper method creates a form that uses the HTTP POST method. You can 
change this so that forms use the GET method, but you should think carefully about doing so. The HTTP 
specification requires that GET requests must be idempotent, meaning that they must not cause changes, and 
adding a product to a cart is definitely a change.*@

    @using (Html.BeginForm("AddToCart", "Cart")) {
        @Html.HiddenFor(x => x.ProductID)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)<input type="submit" value="+ Add to cart" />
    }

    <h4>@Model.Price.ToString("c")</h4>
    @*<h5>@Request.Url.PathAndQuery.ToString();</h5>  *@
</div>

SeeMoreApp.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>

@*    In most situations, client-side validation is a useful feature, but if, for some reason, you don’t want 
to validate at the client, you need to use the following statements: 
 
HtmlHelper.ClientValidationEnabled = false; 
HtmlHelper.UnobtrusiveJavaScriptEnabled = false; *@

@*If you put these statements in a view or in a controller, then client-side validation is disabled only 
for the current action. You can disable client-side validation for the entire application by using those 
statements in the Application_Start method of Global.asax or by adding values to the Web.config file*@

    <link href="@Url.Content("~/Content/Admin.css")" rel="stylesheet" type="text/css" />
     <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"  
        type="text/javascript"></script> 
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"  
        type="text/javascript"></script> 
</head>
<body> 

@*The benefit of dealing with the message in the template like this is that users will see it displayed on 
whatever page is rendered after they have saved a change. At the moment, we return them to the list of products, 
but we could change the workflow to render some other view, and the users will still see the message (as long as 
the next view also uses the same layout)*@

    <div> 
        @if (TempData["message"] != null) { 
            <div class="Message">@TempData["message"]</div> 
        } 
        @RenderBody() 
    </div>
</body>
</html>

SeeMoreApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>

@*     Notice that the CSS and JavaScript files that are referenced in Listing 7-24 are done so using the 
@Url.Content method. Unlike the ASPX view engine, Razor doesn’t automatically interpret the tilde character (~) 
as a reference for the root of the application, so we must do this explicitly using the helper method.*@

    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>

<body>
    <div id="header"> 
        @{Html.RenderAction("Summary", "Cart");}
        <div class="title">SeeMoreApp (Test)</div> 
     </div> 
     <div id="categories"> 

@*     The RenderAction method writes its content directly to the response stream, just like the RenderPartial 
method introduced in Chapter 7. This means that the method returns void, and therefore can’t be used with a 
regular Razor @ tag. Instead, we must enclose the call to the method inside a Razor code block (and remember to 
terminate the statement with a semicolon). You can use the Action method as an alternative if you don’t like this 
code-block syntax.*@

        @{ Html.RenderAction("Menu", "Nav");}
     </div> 
     <div id="content"> 
        @RenderBody() 
    </div>
</body>
</html>